# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 572)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.headerFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.headerLabel = QtWidgets.QLabel(self.headerFrame)
        self.headerLabel.setObjectName("headerLabel")
        self.gridLayout.addWidget(self.headerLabel, 0, 0, 1, 1)
        self.headerContents = QtWidgets.QTextBrowser(self.headerFrame)
        self.headerContents.setObjectName("headerContents")
        self.gridLayout.addWidget(self.headerContents, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.headerFrame, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_7.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 2, 1, 1)
        self.parentGroupFrame = QtWidgets.QFrame(self.centralwidget)
        self.parentGroupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parentGroupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parentGroupFrame.setObjectName("parentGroupFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.parentGroupFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.obsIndexInput = QtWidgets.QLineEdit(self.parentGroupFrame)
        self.obsIndexInput.setObjectName("obsIndexInput")
        self.horizontalLayout.addWidget(self.obsIndexInput)
        self.obsIndexPush = QtWidgets.QPushButton(self.parentGroupFrame)
        self.obsIndexPush.setObjectName("obsIndexPush")
        self.horizontalLayout.addWidget(self.obsIndexPush)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.obsIndexLabel = QtWidgets.QLabel(self.parentGroupFrame)
        self.obsIndexLabel.setObjectName("obsIndexLabel")
        self.gridLayout_6.addWidget(self.obsIndexLabel, 0, 0, 1, 1)
        self.parentGroupLabel = QtWidgets.QLabel(self.parentGroupFrame)
        self.parentGroupLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.parentGroupLabel.setObjectName("parentGroupLabel")
        self.gridLayout_6.addWidget(self.parentGroupLabel, 2, 0, 1, 1)
        self.parentGroupList = QtWidgets.QTextBrowser(self.parentGroupFrame)
        self.parentGroupList.setObjectName("parentGroupList")
        self.gridLayout_6.addWidget(self.parentGroupList, 3, 0, 1, 1)
        self.parentGroupLabel.raise_()
        self.obsIndexInput.raise_()
        self.obsIndexLabel.raise_()
        self.obsIndexLabel.raise_()
        self.parentGroupList.raise_()
        self.gridLayout_3.addWidget(self.parentGroupFrame, 0, 2, 1, 1)
        self.debugFrame = QtWidgets.QFrame(self.centralwidget)
        self.debugFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.debugFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.debugFrame.setObjectName("debugFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.debugFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.debugContents = QtWidgets.QTextBrowser(self.debugFrame)
        self.debugContents.setObjectName("debugContents")
        self.gridLayout_5.addWidget(self.debugContents, 1, 0, 1, 1)
        self.debugLabel = QtWidgets.QLabel(self.debugFrame)
        self.debugLabel.setObjectName("debugLabel")
        self.gridLayout_5.addWidget(self.debugLabel, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.debugFrame, 1, 0, 1, 1)
        self.availableGroupFrame = QtWidgets.QFrame(self.centralwidget)
        self.availableGroupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.availableGroupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.availableGroupFrame.setObjectName("availableGroupFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.availableGroupFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupContents = QtWidgets.QListWidget(self.availableGroupFrame)
        self.groupContents.setObjectName("groupContents")
        self.gridLayout_4.addWidget(self.groupContents, 2, 0, 1, 1)
        self.groupLabel = QtWidgets.QLabel(self.availableGroupFrame)
        self.groupLabel.setObjectName("groupLabel")
        self.gridLayout_4.addWidget(self.groupLabel, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.availableGroupFrame, 1, 1, 1, 1)
        self.variableFrame = QtWidgets.QFrame(self.centralwidget)
        self.variableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.variableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.variableFrame.setObjectName("variableFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.variableFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.variableLabel = QtWidgets.QLabel(self.variableFrame)
        self.variableLabel.setObjectName("variableLabel")
        self.gridLayout_2.addWidget(self.variableLabel, 0, 0, 1, 1)
        self.variableList = QtWidgets.QListWidget(self.variableFrame)
        self.variableList.setObjectName("variableList")
        self.gridLayout_2.addWidget(self.variableList, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.variableFrame, 0, 1, 1, 1)
        self.headerFrame.raise_()
        self.variableFrame.raise_()
        self.debugFrame.raise_()
        self.availableGroupFrame.raise_()
        self.parentGroupFrame.raise_()
        self.debugLabel.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCreate_Plot = QtWidgets.QAction(MainWindow)
        self.actionCreate_Plot.setObjectName("actionCreate_Plot")
        self.actionSave_Plot = QtWidgets.QAction(MainWindow)
        self.actionSave_Plot.setObjectName("actionSave_Plot")
        self.actionCombine_Plot = QtWidgets.QAction(MainWindow)
        self.actionCombine_Plot.setObjectName("actionCombine_Plot")
        self.actionView_Documentation = QtWidgets.QAction(MainWindow)
        self.actionView_Documentation.setObjectName("actionView_Documentation")
        self.menuFile.addAction(self.actionOpen)
        self.menuPlot.addAction(self.actionCreate_Plot)
        self.menuPlot.addAction(self.actionSave_Plot)
        self.menuPlot.addAction(self.actionCombine_Plot)
        self.menuHelp.addAction(self.actionView_Documentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "netCDF Plotting GUI"))
        self.headerLabel.setText(_translate("MainWindow", "Header Contents"))
        self.label.setText(_translate("MainWindow", "Dummy"))
        self.obsIndexPush.setText(_translate("MainWindow", "Go"))
        self.obsIndexLabel.setText(_translate("MainWindow", "Observation Index"))
        self.parentGroupLabel.setText(_translate("MainWindow", "Parent Groups"))
        self.debugLabel.setText(_translate("MainWindow", "Debug Broswer"))
        self.groupLabel.setText(_translate("MainWindow", "Available Groups in Dataset"))
        self.variableLabel.setText(_translate("MainWindow", "Variable Contents"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionCreate_Plot.setText(_translate("MainWindow", "Create Plot"))
        self.actionSave_Plot.setText(_translate("MainWindow", "Save Plot"))
        self.actionCombine_Plot.setText(_translate("MainWindow", "Combine Plot"))
        self.actionView_Documentation.setText(_translate("MainWindow", "View Documentation"))

