# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 582)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(12, 12, 361, 521))
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.headerFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.headerLabel = QtWidgets.QLabel(self.headerFrame)
        self.headerLabel.setObjectName("headerLabel")
        self.gridLayout.addWidget(self.headerLabel, 0, 0, 1, 1)
        self.headerContents = QtWidgets.QTextBrowser(self.headerFrame)
        self.headerContents.setStyleSheet("background-color: rgb(244, 255, 245)")
        self.headerContents.setObjectName("headerContents")
        self.gridLayout.addWidget(self.headerContents, 1, 0, 1, 1)
        self.variableFrame = QtWidgets.QFrame(self.centralwidget)
        self.variableFrame.setGeometry(QtCore.QRect(380, 10, 250, 521))
        self.variableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.variableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.variableFrame.setObjectName("variableFrame")
        self.variableLabel = QtWidgets.QLabel(self.variableFrame)
        self.variableLabel.setGeometry(QtCore.QRect(13, 13, 109, 16))
        self.variableLabel.setObjectName("variableLabel")
        self.variableList = QtWidgets.QListWidget(self.variableFrame)
        self.variableList.setGeometry(QtCore.QRect(13, 37, 224, 191))
        self.variableList.setObjectName("variableList")
        self.groupContents = QtWidgets.QListWidget(self.variableFrame)
        self.groupContents.setGeometry(QtCore.QRect(13, 262, 224, 192))
        self.groupContents.setObjectName("groupContents")
        self.groupLabel = QtWidgets.QLabel(self.variableFrame)
        self.groupLabel.setGeometry(QtCore.QRect(13, 238, 167, 16))
        self.groupLabel.setObjectName("groupLabel")
        self.plotButton = QtWidgets.QPushButton(self.variableFrame)
        self.plotButton.setGeometry(QtCore.QRect(170, 460, 66, 32))
        self.plotButton.setObjectName("plotButton")
        self.parentGroupFrame = QtWidgets.QFrame(self.centralwidget)
        self.parentGroupFrame.setGeometry(QtCore.QRect(640, 10, 282, 521))
        self.parentGroupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parentGroupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parentGroupFrame.setObjectName("parentGroupFrame")
        self.obsIndexLabel = QtWidgets.QLabel(self.parentGroupFrame)
        self.obsIndexLabel.setGeometry(QtCore.QRect(13, 13, 251, 16))
        self.obsIndexLabel.setObjectName("obsIndexLabel")
        self.parentGroupLabel = QtWidgets.QLabel(self.parentGroupFrame)
        self.parentGroupLabel.setGeometry(QtCore.QRect(13, 80, 88, 16))
        self.parentGroupLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.parentGroupLabel.setObjectName("parentGroupLabel")
        self.parentGroupList = QtWidgets.QTextBrowser(self.parentGroupFrame)
        self.parentGroupList.setGeometry(QtCore.QRect(13, 104, 256, 121))
        self.parentGroupList.setObjectName("parentGroupList")
        self.debugLabel = QtWidgets.QLabel(self.parentGroupFrame)
        self.debugLabel.setGeometry(QtCore.QRect(10, 236, 94, 16))
        self.debugLabel.setObjectName("debugLabel")
        self.debugContents = QtWidgets.QTextBrowser(self.parentGroupFrame)
        self.debugContents.setGeometry(QtCore.QRect(10, 260, 256, 192))
        self.debugContents.setObjectName("debugContents")
        self.widget = QtWidgets.QWidget(self.parentGroupFrame)
        self.widget.setGeometry(QtCore.QRect(13, 37, 251, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.obsIndexInput = QtWidgets.QLineEdit(self.widget)
        self.obsIndexInput.setObjectName("obsIndexInput")
        self.horizontalLayout.addWidget(self.obsIndexInput)
        self.obsIndexPush = QtWidgets.QPushButton(self.widget)
        self.obsIndexPush.setObjectName("obsIndexPush")
        self.horizontalLayout.addWidget(self.obsIndexPush)
        self.parentGroupLabel.raise_()
        self.obsIndexLabel.raise_()
        self.parentGroupList.raise_()
        self.debugLabel.raise_()
        self.debugContents.raise_()
        self.headerFrame.raise_()
        self.obsIndexLabel.raise_()
        self.variableFrame.raise_()
        self.parentGroupFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCreate_Plot = QtWidgets.QAction(MainWindow)
        self.actionCreate_Plot.setObjectName("actionCreate_Plot")
        self.actionSave_Plot = QtWidgets.QAction(MainWindow)
        self.actionSave_Plot.setObjectName("actionSave_Plot")
        self.actionCombine_Plot = QtWidgets.QAction(MainWindow)
        self.actionCombine_Plot.setObjectName("actionCombine_Plot")
        self.actionView_Documentation = QtWidgets.QAction(MainWindow)
        self.actionView_Documentation.setObjectName("actionView_Documentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionOpen)
        self.menuPlot.addAction(self.actionCreate_Plot)
        self.menuPlot.addAction(self.actionSave_Plot)
        self.menuPlot.addAction(self.actionCombine_Plot)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionView_Documentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DART Viewer"))
        self.headerLabel.setText(_translate("MainWindow", "Header Contents"))
        self.variableLabel.setText(_translate("MainWindow", "Variable Contents"))
        self.groupLabel.setText(_translate("MainWindow", "Group Contents"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.obsIndexLabel.setText(_translate("MainWindow", "Group Lookup via Observation Index"))
        self.parentGroupLabel.setText(_translate("MainWindow", "Parent Groups"))
        self.debugLabel.setText(_translate("MainWindow", "Debug Broswer"))
        self.obsIndexPush.setText(_translate("MainWindow", "Find"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionCreate_Plot.setText(_translate("MainWindow", "Create Plot"))
        self.actionSave_Plot.setText(_translate("MainWindow", "Save Plot"))
        self.actionCombine_Plot.setText(_translate("MainWindow", "Combine Plot"))
        self.actionView_Documentation.setText(_translate("MainWindow", "View Documentation"))
        self.actionAbout.setText(_translate("MainWindow", "About DART Viewer"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionNew.setText(_translate("MainWindow", "New"))
