# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/designer/subset_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_subset_dialog(object):
    def setupUi(self, subset_dialog):
        subset_dialog.setObjectName("subset_dialog")
        subset_dialog.resize(388, 459)
        self.gridLayout_2 = QtWidgets.QGridLayout(subset_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(subset_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(subset_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.lon_max_label = QtWidgets.QLabel(self.frame)
        self.lon_max_label.setObjectName("lon_max_label")
        self.gridLayout.addWidget(self.lon_max_label, 0, 1, 1, 1)
        self.lat_max_label = QtWidgets.QLabel(self.frame)
        self.lat_max_label.setObjectName("lat_max_label")
        self.gridLayout.addWidget(self.lat_max_label, 2, 1, 1, 1)
        self.lat_min_label = QtWidgets.QLabel(self.frame)
        self.lat_min_label.setObjectName("lat_min_label")
        self.gridLayout.addWidget(self.lat_min_label, 2, 0, 1, 1)
        self.time_min_label = QtWidgets.QLabel(self.frame)
        self.time_min_label.setObjectName("time_min_label")
        self.gridLayout.addWidget(self.time_min_label, 4, 0, 1, 1)
        self.lon_min_input = QtWidgets.QLineEdit(self.frame)
        self.lon_min_input.setText("")
        self.lon_min_input.setObjectName("lon_min_input")
        self.gridLayout.addWidget(self.lon_min_input, 1, 0, 1, 1)
        self.lat_min_input = QtWidgets.QLineEdit(self.frame)
        self.lat_min_input.setObjectName("lat_min_input")
        self.gridLayout.addWidget(self.lat_min_input, 3, 0, 1, 1)
        self.time_max_input = QtWidgets.QLineEdit(self.frame)
        self.time_max_input.setText("")
        self.time_max_input.setObjectName("time_max_input")
        self.gridLayout.addWidget(self.time_max_input, 5, 1, 1, 1)
        self.time_max_label = QtWidgets.QLabel(self.frame)
        self.time_max_label.setObjectName("time_max_label")
        self.gridLayout.addWidget(self.time_max_label, 4, 1, 1, 1)
        self.lat_max_input = QtWidgets.QLineEdit(self.frame)
        self.lat_max_input.setObjectName("lat_max_input")
        self.gridLayout.addWidget(self.lat_max_input, 3, 1, 1, 1)
        self.time_min_input = QtWidgets.QLineEdit(self.frame)
        self.time_min_input.setText("")
        self.time_min_input.setObjectName("time_min_input")
        self.gridLayout.addWidget(self.time_min_input, 5, 0, 1, 1)
        self.lon_max_input = QtWidgets.QLineEdit(self.frame)
        self.lon_max_input.setObjectName("lon_max_input")
        self.gridLayout.addWidget(self.lon_max_input, 1, 1, 1, 1)
        self.lon_min_label = QtWidgets.QLabel(self.frame)
        self.lon_min_label.setObjectName("lon_min_label")
        self.gridLayout.addWidget(self.lon_min_label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qc_values_label = QtWidgets.QLabel(self.frame)
        self.qc_values_label.setObjectName("qc_values_label")
        self.verticalLayout.addWidget(self.qc_values_label)
        self.qc_checkbox_8 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_8.setObjectName("qc_checkbox_8")
        self.verticalLayout.addWidget(self.qc_checkbox_8)
        self.qc_checkbox_0 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_0.setObjectName("qc_checkbox_0")
        self.verticalLayout.addWidget(self.qc_checkbox_0)
        self.qc_checkbox_1 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_1.setObjectName("qc_checkbox_1")
        self.verticalLayout.addWidget(self.qc_checkbox_1)
        self.qc_checkbox_2 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_2.setObjectName("qc_checkbox_2")
        self.verticalLayout.addWidget(self.qc_checkbox_2)
        self.qc_checkbox_3 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_3.setObjectName("qc_checkbox_3")
        self.verticalLayout.addWidget(self.qc_checkbox_3)
        self.qc_checkbox_4 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_4.setObjectName("qc_checkbox_4")
        self.verticalLayout.addWidget(self.qc_checkbox_4)
        self.qc_checkbox_5 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_5.setObjectName("qc_checkbox_5")
        self.verticalLayout.addWidget(self.qc_checkbox_5)
        self.qc_checkbox_6 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_6.setObjectName("qc_checkbox_6")
        self.verticalLayout.addWidget(self.qc_checkbox_6)
        self.qc_checkbox_7 = QtWidgets.QCheckBox(self.frame)
        self.qc_checkbox_7.setObjectName("qc_checkbox_7")
        self.verticalLayout.addWidget(self.qc_checkbox_7)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(subset_dialog)
        self.buttonBox.accepted.connect(subset_dialog.accept)
        self.buttonBox.rejected.connect(subset_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(subset_dialog)

    def retranslateUi(self, subset_dialog):
        _translate = QtCore.QCoreApplication.translate
        subset_dialog.setWindowTitle(_translate("subset_dialog", "Dialog"))
        self.lon_max_label.setText(_translate("subset_dialog", "Lon max"))
        self.lat_max_label.setText(_translate("subset_dialog", "Lat max"))
        self.lat_min_label.setText(_translate("subset_dialog", "Lat min"))
        self.time_min_label.setText(_translate("subset_dialog", "Time min"))
        self.time_max_label.setText(_translate("subset_dialog", "Time max"))
        self.lon_min_label.setText(_translate("subset_dialog", "Lon min"))
        self.qc_values_label.setText(_translate("subset_dialog", "DART QC Values"))
        self.qc_checkbox_8.setText(_translate("subset_dialog", "All"))
        self.qc_checkbox_0.setText(_translate("subset_dialog", "Assimilated"))
        self.qc_checkbox_1.setText(_translate("subset_dialog", "Evaluated only"))
        self.qc_checkbox_2.setText(_translate("subset_dialog", "Assimilated but posterior forward operator failed"))
        self.qc_checkbox_3.setText(_translate("subset_dialog", "Evaluated only but posterior forward operator failed"))
        self.qc_checkbox_4.setText(_translate("subset_dialog", "Not used, prior forward operator failed"))
        self.qc_checkbox_5.setText(_translate("subset_dialog", "Not used, not selected in obs_kind_nml"))
        self.qc_checkbox_6.setText(_translate("subset_dialog", "Not used, failed prior QC check"))
        self.qc_checkbox_7.setText(_translate("subset_dialog", "Violated outlier threshold"))

