# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/designer/subset_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_subset_dialog(object):
    def setupUi(self, subset_dialog):
        subset_dialog.setObjectName("subset_dialog")
        subset_dialog.resize(373, 327)
        self.gridLayout_2 = QtWidgets.QGridLayout(subset_dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(subset_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(subset_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.lon_min_label = QtWidgets.QLabel(self.frame)
        self.lon_min_label.setObjectName("lon_min_label")
        self.gridLayout.addWidget(self.lon_min_label, 0, 0, 1, 1)
        self.lon_max_label = QtWidgets.QLabel(self.frame)
        self.lon_max_label.setObjectName("lon_max_label")
        self.gridLayout.addWidget(self.lon_max_label, 0, 1, 1, 1)
        self.lon_min_input = QtWidgets.QLineEdit(self.frame)
        self.lon_min_input.setText("")
        self.lon_min_input.setObjectName("lon_min_input")
        self.gridLayout.addWidget(self.lon_min_input, 1, 0, 1, 1)
        self.lon_max_input = QtWidgets.QLineEdit(self.frame)
        self.lon_max_input.setObjectName("lon_max_input")
        self.gridLayout.addWidget(self.lon_max_input, 1, 1, 1, 1)
        self.lat_min_label = QtWidgets.QLabel(self.frame)
        self.lat_min_label.setObjectName("lat_min_label")
        self.gridLayout.addWidget(self.lat_min_label, 2, 0, 1, 1)
        self.lat_max_label = QtWidgets.QLabel(self.frame)
        self.lat_max_label.setObjectName("lat_max_label")
        self.gridLayout.addWidget(self.lat_max_label, 2, 1, 1, 1)
        self.lat_min_input = QtWidgets.QLineEdit(self.frame)
        self.lat_min_input.setObjectName("lat_min_input")
        self.gridLayout.addWidget(self.lat_min_input, 3, 0, 1, 1)
        self.lat_max_input = QtWidgets.QLineEdit(self.frame)
        self.lat_max_input.setObjectName("lat_max_input")
        self.gridLayout.addWidget(self.lat_max_input, 3, 1, 1, 1)
        self.time_min_label = QtWidgets.QLabel(self.frame)
        self.time_min_label.setObjectName("time_min_label")
        self.gridLayout.addWidget(self.time_min_label, 4, 0, 1, 1)
        self.time_max_label = QtWidgets.QLabel(self.frame)
        self.time_max_label.setObjectName("time_max_label")
        self.gridLayout.addWidget(self.time_max_label, 4, 1, 1, 1)
        self.time_min_input = QtWidgets.QLineEdit(self.frame)
        self.time_min_input.setText("")
        self.time_min_input.setObjectName("time_min_input")
        self.gridLayout.addWidget(self.time_min_input, 5, 0, 1, 1)
        self.time_max_input = QtWidgets.QLineEdit(self.frame)
        self.time_max_input.setText("")
        self.time_max_input.setObjectName("time_max_input")
        self.gridLayout.addWidget(self.time_max_input, 5, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_min_label_2 = QtWidgets.QLabel(self.frame)
        self.time_min_label_2.setObjectName("time_min_label_2")
        self.verticalLayout.addWidget(self.time_min_label_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(subset_dialog)
        self.buttonBox.accepted.connect(subset_dialog.accept)
        self.buttonBox.rejected.connect(subset_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(subset_dialog)

    def retranslateUi(self, subset_dialog):
        _translate = QtCore.QCoreApplication.translate
        subset_dialog.setWindowTitle(_translate("subset_dialog", "Dialog"))
        self.lon_min_label.setText(_translate("subset_dialog", "Lon min"))
        self.lon_max_label.setText(_translate("subset_dialog", "Lon max"))
        self.lat_min_label.setText(_translate("subset_dialog", "Lat min"))
        self.lat_max_label.setText(_translate("subset_dialog", "Lat max"))
        self.time_min_label.setText(_translate("subset_dialog", "Time min"))
        self.time_max_label.setText(_translate("subset_dialog", "Time max"))
        self.time_min_label_2.setText(_translate("subset_dialog", "DART QC Values"))
        self.checkBox.setText(_translate("subset_dialog", "Assimilated OK"))
        self.checkBox_2.setText(_translate("subset_dialog", "Outliers"))

